[tool.black]
line-length = 100
target-version = ['py39', 'py310', 'py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  migrations
  | venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 100
skip = ["migrations", "venv"]

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true
strict = false
warn_return_any = true
warn_unused_configs = true
no_implicit_reexport = true