#!/bin/bash

# Cursor Chat Saver Script
# Usage: ./scripts/save-cursor-chat.sh

DATE=$(date +%Y%m%d-%H%M%S)
SESSION_DIR="claudedocs/sessions"
FILENAME="cursor-session-${DATE}.md"
FILEPATH="${SESSION_DIR}/${FILENAME}"

# Create directory if not exists
mkdir -p ${SESSION_DIR}

# Create session file
cat > ${FILEPATH} << 'EOF'
# Cursor Session Log

## Date: 
## Time: 

## Conversation Content
[ここに会話内容を貼り付け]

## Commands Used
```bash
# ここに使用したコマンドを記録
```

## Key Decisions
- 

## Files Modified
- 

## Notes
- 

---
*Auto-generated by save-cursor-chat.sh*
EOF

echo "📝 Session file created: ${FILEPATH}"
echo "👉 Please copy your Cursor conversation and paste it into the file"
echo "   File location: $(pwd)/${FILEPATH}"

# Open in default editor (optional)
# code ${FILEPATH}  # VSCode/Cursor
# open ${FILEPATH}  # macOS default editor