apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mail-score-base

resources:
  - namespace.yaml
  - postgres.yaml
  - redis.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - monitoring.yaml

commonLabels:
  app.kubernetes.io/part-of: mail-score
  app.kubernetes.io/managed-by: kustomize

images:
  - name: mail-score-backend
    newTag: latest
  - name: mail-score-frontend
    newTag: latest

configMapGenerator:
  - name: deployment-config
    literals:
      - DEPLOYMENT_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
      - KUBERNETES_VERSION=v1.28

secretGenerator:
  - name: tls-secret
    files:
      - tls.crt
      - tls.key
    type: kubernetes.io/tls

replacements:
  - source:
      kind: ConfigMap
      name: deployment-config
      fieldPath: data.DEPLOYMENT_DATE
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - metadata.annotations.[deployment/date]

patches:
  - target:
      kind: Deployment
      name: mail-score-backend
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          deployment.kubernetes.io/revision: "1"

  - target:
      kind: Deployment
      name: mail-score-frontend
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          deployment.kubernetes.io/revision: "1"